"""Initial migration

Revision ID: 44850d1382e9
Revises: 
Create Date: 2024-11-25 00:49:17.656676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44850d1382e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
    sa.Column('chartId', sa.Integer(), nullable=False),
    sa.Column('chartType', sa.String(), nullable=False),
    sa.Column('generatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chartId')
    )
    op.create_index(op.f('ix_charts_chartId'), 'charts', ['chartId'], unique=False)
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_pw', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_userId'), 'users', ['userId'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('followedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.userId'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_table('playlists',
    sa.Column('playlistId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('playlist_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('playlistId')
    )
    op.create_index(op.f('ix_playlists_playlistId'), 'playlists', ['playlistId'], unique=False)
    op.create_table('songs',
    sa.Column('songId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('album', sa.String(), nullable=False),
    sa.Column('spotify_url', sa.String(), nullable=False),
    sa.Column('album_cover_url', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('sharedBy', sa.Integer(), nullable=True),
    sa.Column('sharedAt', sa.DateTime(), nullable=True),
    sa.Column('reaction', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sharedBy'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('songId')
    )
    op.create_index(op.f('ix_songs_songId'), 'songs', ['songId'], unique=False)
    op.create_table('chart_songs',
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.chartId'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.songId'], ),
    sa.PrimaryKeyConstraint('chart_id', 'song_id')
    )
    op.create_table('playlist_songs',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.playlistId'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.songId'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_songs')
    op.drop_table('chart_songs')
    op.drop_index(op.f('ix_songs_songId'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_playlists_playlistId'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_users_userId'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_charts_chartId'), table_name='charts')
    op.drop_table('charts')
    # ### end Alembic commands ###
